live_config_reload = true

# import = ["~/.config/alacritty/themes/themes/ayu_light.toml"]
import = ["~/.config/alacritty/themes/themes/catppuccin_latte.toml"]

[window]
opacity = 0.8
option_as_alt = "OnlyLeft"

[window.padding]
# decoration = "none"
# dynamic_padding = true
x = 10
y = 10

[font]
size = 14

[font.bold]
family = "JetBrainsMono Nerd Font"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"

[font.italic]
family = "JetBrainsMono Nerd Font"

[font.normal]
family = "JetBrainsMono Nerd Font"

[mouse]
hide_when_typing = true
