theme = "base16_default"

[editor]
line-number = "relative"
mouse = false
auto-format = true
# rulers = [120]

[editor.indent-guides]
character = "╎"
render = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.lsp]
# Disable automatically popups of signature parameter help
auto-signature-help = false
# Show LSP messages in the status line
display-messages = true

[editor.file-picker]
hidden = false


[keys.normal]
esc = [ "collapse_selection", "keep_primary_selection"]

[editor.soft-wrap]
enable = true
max-wrap = 25 # increase value to reduce forced mid-word wrapping
max-indent-retain = 40
wrap-indicator = ""  # set wrap-indicator to "" to hide it
