theme = "base16_default"

[editor]
line-number = "relative"
mouse = false
auto-format = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.normal]
esc = [ "collapse_selection", "keep_primary_selection"]
